#!/bin/bash -l
#
# Job: This job run 8 jobs in two nodes
#
#
# qg09 version 1.0.7
#
# To submit this script to the queue type:
#    qsub a001.pbs
#
#PBS -m n
#PBS -l nodes=4:ppn=4
#PBS -l walltime=00:60:00
#PBS -l pmem=1000mb
#PBS -e s.e
#PBS -o s.o
#PBS -q devel 
#
cd $PBS_O_WORKDIR

module load ompi/1.8.5/intel-2015-update3 
export MOPAC_LICENSE=/home/truhlard/meanapan/soft/MOPAC
mpirun -np 4 --map-by node ./mpiq.exe > logfile
#mpirun -np 2 ../mpiq.exe > logfile
