nguage: fortran 
sudo: required
before_install:
  - sudo apt-get install gfortran openmpi

script:
  - mpif90 mpiqf.f90 -o mpiq.exe 
  - cd test; ./mpiq.exe

after_success:
- bash <(echo "Successfull test!)
