#!/bin/bash -l
#
# Job: Example
#
# To submit this script to the queue type:
#    qsub mpiq.pbs
#
#PBS -m n
#PBS -l nodes=2:ppn=8
#PBS -l walltime=24:00:00
#PBS -l pmem=2000mb
#PBS -e err.e
#PBS -o err.o
#PBS -q batch 
#
cd $PBS_O_WORKDIR

module load gaussian/g09.a02.mngfm50  
export GAUSS_SCRDIR=/scratch/meanapan
mkdir -p /scratch/meanapan

## Use Intel MPI 
module load intel mpi
# Each job in one node
mpirun -np 2 --map-by node $HOME/soft/bin/mpicola.exe > logfile 


